// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"go-gin-init-v2/app/config"
	"go-gin-init-v2/app/handler"
	"go-gin-init-v2/app/repository"
	"go-gin-init-v2/app/service"
)

// Injectors from wire.go:

func InitializeApplication() (APIApplication, error) {
	configConfig, err := config.Load()
	if err != nil {
		return APIApplication{}, err
	}
	db := config.ConnectDB(configConfig)
	repositoryDefault := repository.NewDefault(db)
	serviceDefault := service.NewDefault(repositoryDefault)
	handlerDefault := handler.NewDefault(serviceDefault)
	engine := config.SetupRouter(handlerDefault)
	apiApplication := NewAPIApplication(configConfig, engine, db)
	return apiApplication, nil
}
